### ISSUE TITLE
What repo is best to use

### ISSUE THREAD

**Issue by phildotdev** [assemble/assemble-core#1]
Hi,

I use grunt-assemble (v0.4) for my production projects but would like to update to a later version as I now use Gulp for things. I have been following Assemble 0.6.0 development for a while but have become a bit confused as to what is recommended/in development as there is the 'assemble' repo and now this one. 

I appreciate everything is WIP right now but I'd like to start testing. Would you recommend using assemble-core? I use metalsmith in a reasonably similar way to this seems like the right repo.

Thanks.

**Comment by jonschlinkert** [comment]
Yeah assemble-core is a good way to start, have you [seen the examples](https://github.com/assemble/assemble-core/tree/master/examples)?

**Comment by phildotdev** [comment]
Thanks for replying so quickly. I did notice the examples but I was pretty confused by them as they all seem to use different things and none of them use assemble-core. Are they WIP?

Finally, does this mean https://github.com/assemble/assemble is now depricated?

**Comment by jonschlinkert** [comment]
no, assemble-core is the primary, bare bones application that powers assemble v0.6.0.  https://github.com/assemble/assemble is assemble v0.6.0, which, in addition to assemble-core, will ship with additional features like automatically resolving `assets` paths, built-in template types (like `pages`, `partials` and `layouts`, etc).

We're very, very actively developing assemble. many hundreds of commits. but not all commits happen on the assemble repo directly. To reach our goals, we had to create a number of libraries from the ground up to make assemble as awesome as we know it can be.

**Comment by jonschlinkert** [comment]
> Thanks for replying so quickly. I did notice the examples but I was pretty confused by them as they all seem to use different things and none of them use assemble-core. Are they WIP?

No, all of them use assemble-core. Look at the file in the [root of the examples](https://github.com/assemble/assemble-core/blob/master/examples/smithy.js#L7), the examples are based on metalsmith's (since metalsmith is pretty awesome too and has nice examples, we just wanted to show how you would use assemble to accomplish the same goals).

edit: when docs are released this will make more sense. assemble v0.6.0 is extremely pluggable and empowers you to make your own applications, like the examples. To that end, some of things you see in the assemble-core examples (as plugins) might possibly be included in assemble by default.

**Comment by phildotdev** [comment]
Sorry, I should have worded that better as I wasn't suggesting Assemble wasn't being developed I was enquiring about that specific repo.

Thanks for the information, I've got enough to do some quick research this weekend. Thanks.

**Comment by jonschlinkert** [comment]
hey no problem, I didn't take it badly, it was a legit question. We need to do a better job of communicating about where things are. Right now it's a tradeoff, we're spending more time on development, but soon our time will shift to community and docs. we're very close to reaching the goals we set about a year and half ago :)

**Comment by jonschlinkert** [comment]
closing since not really and issue an I think it was resolved. please reopen or create a new issue if you have other questions
