### ISSUE TITLE
Process stuck after first partial

### ISSUE THREAD

**Issue by rparree** [assemble/assemble-core#4]
So i am trying to migrate from `0.4.42` to `assemble-core` mostly to cleanup and speed the build process.

I have been using the `jekyll` example and the many test cases to migrate my first batch of pages.

I have layouts referencing partials (all using hbs).

example layout (`default.hbs`):

```
<!DOCTYPE html>
<html lang="en">
<head>
    {{partial "header"}}
</head>
<body>
  {{partial "nav-main-public"}} 
  {% body %}
  {{> footer }}
</body>
</html>
```

Example partial (`header.hbs`)

```
<meta charset="utf-8">
<meta name="keywords" content="{{ site.keywords }}">
<title>
    {{title}}
</title>

<link rel="stylesheet" href="{{vendor}}/fontawesome/css/font-awesome.css"/>
```

An example page

```

---
layout: default
title: About us

---
blabla yada yada yada
```

My build  adds the layout and partial layouts:

``` javascript
app.create('layouts', {
    viewType: 'layout',
    engine: '*',
    renameKey: function (key) {
        return path.basename(key, ".hbs");
    }
});
app.create('partials', {
    viewType: 'partial',
    engine: '*',
    renameKey: function (key) {
    return path.basename(key, ".hbs");
}});
```

The task looks like

``` javascript
app.task('site', function () {
    app.layouts('./_layouts/*.hbs');
    app.partials('./_includes/*.hbs');
    return app.src('./pages/!(blog)/*.hbs')
        .pipe(app.renderFile('*'))
        .pipe(extname())
        .pipe(app.dest('./build/'));
});
```

When running i see (i have  `preRender` logger)

```
starting site
rendering > about/about.hbs
rendering > header.hbs
```

And then the process just "hangs", it never terminates (and using 100% of a core)

**Comment by rparree** [comment]
Never mind, solved by removing the `node_builds` and reinstalled all again

**Comment by jonschlinkert** [comment]
glad you got it working. the newest version of node/npm is especially finicky with this
