### ISSUE TITLE
The jekyll example does not render the markdown

### ISSUE THREAD

**Issue by rparree** [assemble/assemble-core#5]
The posts in the [jekyll](https://github.com/assemble/assemble-core/tree/master/examples/jekyll) are not using any markdown. When adding markdown syntax, the results are not rendered. 

For example change the `2012-08-20-first-post.md` to

``` markdown
An **interesting** post about how it's going to be different this time around. I'm going write a lot more nowadays and use this blog to improve my writing.
```

The resulting `2012-08-20-first-post.html` has the unprocessed markdown in its `body`

``` html
<!DOCTYPE html>
  <html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>My Blog</title>
  </head>
  <body>
    <h1>First Post</h1>
    <time></time>
    An **interesting** post about how it's going to be different this time around. I'm going write a lot more nowadays and use this blog to improve my writing.
  </body>
</html>
```

This is in fact the same problem i am having with my migration.

**Comment by jonschlinkert** [comment]
We use helpers for markdown, in all versions of assemble. You should be able to use  https://github.com/helpers/helper-md or https://github.com/helpers/helper-markdown for this. I'll add this to the example too in a little bit. Fwiw I think I just ported the example the way it was in metalsmith

**Comment by rparree** [comment]
I have been trying that (as the code uses the  `{{#markdown}}` helper within assemble 0.4.42. 

I registed my own helper. I have been looking into `assemble-core/node_modules/templates/node_modules/load-helpers/index.js` to see how i could register the `handlebars-helper`. Should i use another helper library?
